# Site settings
title: 一般社団法人自然体験村
description: 新潟県南魚沼市の子ども向け自然体験キャンプ
baseurl: ""
url: ""

# Build settings
markdown: kramdown
permalink: pretty
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
include:
  - admin
