locale: 'ja'
backend:
  name: git-gateway
  # name: github
  # repo: ukkari/taikenmura
  branch: main
  # auth_scope: repo # GitHubのリポジトリにアクセスするために必要

publish_mode: editorial_workflow

# Netlify Identityを使用
identity_backend:
  name: netlify-identity

# 画像や添付ファイルのアップロード設定
media_folder: "images/uploads"
public_folder: "/images/uploads"

# コレクション設定
collections:
  # メインページのコレクション
  - name: "pages"
    label: "メインページ"
    preview_path: previews/index
    editor:
      preview: false
    files:
      - name: "home"
        label: "ホームページ"
        file: "index.html"
        format: "frontmatter"
        fields:
          - {label: "レイアウト", name: "layout", widget: "hidden", default: "default"}
          - {label: "タイトル", name: "title", widget: "string"}
          - {label: "カスタムCSS", name: "custom_css", widget: "text", required: false}
          - {label: "本文", name: "body", widget: "code", default_language: "html", output_code_only: true}

  # セクションページのコレクション
  - name: "sections"
    label: "セクションページ"
    editor:
      preview: false
    preview_path: previews/sections/
    folder: "sections"
    create: false
    extension: "html"
    format: "frontmatter"
    fields:
      - {label: "レイアウト", name: "layout", widget: "hidden", default: "default"}
      - {label: "タイトル", name: "title", widget: "string"}
      - {label: "本文", name: "body", widget: "code", default_language: "html", output_code_only: true}

  # インクルードファイルのコレクション
  - name: "includes"
    label: "共通コンポーネント"
    editor:
      preview: false
    files:
      - name: "header"
        label: "ヘッダー"
        file: "_includes/header.html"
        format: "raw"
        fields:
          - {label: "本文", name: "body", widget: "code", default_language: "html", output_code_only: true}
      - name: "footer"
        label: "フッター"
        file: "_includes/footer.html"
        format: "raw"
        fields:
          - {label: "本文", name: "body", widget: "code", default_language: "html", output_code_only: true}
  
  # レイアウトファイルのコレクション
  - name: "layouts"
    label: "レイアウト"
    editor:
      preview: false
    files:
      - name: "default"
        label: "デフォルトレイアウト"
        file: "_layouts/default.html"
        format: "raw"
        fields:
          - {label: "本文", name: "body", widget: "code", default_language: "html", output_code_only: true}
          
  # FAQデータのコレクション
  - name: "data"
    label: "データファイル"
    editor:
      preview: false
    files:
      - name: "faqs"
        label: "よくある質問"
        file: "_data/faqs.yml"
        format: "yml"
        description: "よくある質問（FAQ）のデータ"
        fields:
          - name: ""
            label: カテゴリ
            widget: list
            fields:
              - {label: "カテゴリ名", name: "category", widget: "string"}
              - name: questions
                label: 質問
                widget: list
                fields:
                  - {label: "質問", name: "question", widget: "string"}
                  - {label: "回答", name: "answer", widget: "text"}
                  - {label: "トップページに表示", name: "featured", widget: "boolean", default: false, required: false}
                  - {label: "画像", name: "image", widget: "image", required: false}
